name: app_treinamento
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  email_validator: ^1.0.5
  mobx: ^1.0.0
  flutter_mobx: ^1.0.0
  cupertino_icons: ^0.1.3
  # flutter_blue: ^0.6.3+1
  flutter_beacon: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.2
  mobx_codegen: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/imagens/logo1.jpg
